### ISSUE TITLE
Coscheduling: When the resource is sufficient, the pod is always Pending

### ISSUE THREAD

**Issue by liiitleboy** [kubernetes-sigs/scheduler-plugins#114]
apiVersion: "batch/v1"
kind: "Job"
metadata:
  namespace: test-ns
  name: tf-work-1
spec:
  template:
    metadata:
      labels:
        pod-group.scheduling.sigs.k8s.io/name: tf-work
        pod-group.scheduling.sigs.k8s.io/min-available: "2"
    spec:
      restartPolicy: "OnFailure"
      containers:
        - image: myimage
          name: tf-work-1
          command: [ "/bin/sh","-c","top -b" ]
          resources:
            limits:
              cpu: "6"
              memory: 8Gi
            requests:
              cpu: "6"
              memory: 8Gi

apiVersion: "batch/v1"
kind: "Job"
metadata:
  namespace: test-ns
  name: tf-work-2
spec:
  template:
    metadata:
      labels:
        pod-group.scheduling.sigs.k8s.io/name: tf-work
        pod-group.scheduling.sigs.k8s.io/min-available: "2"
    spec:
      restartPolicy: "OnFailure"
      containers:
        - image: myimage
          name: tf-work-2
          command: [ "/bin/sh","-c","top -b" ]
          resources:
            limits:
              cpu: "6"
              memory: 8Gi
            requests:
              cpu: "6"
              memory: 8Gi

`E1124 12:15:02.731405       1 factory.go:601] Error scheduling test-ns/tf-work-1-qbtz6: rejected by "coscheduling" at prefilter: less than minAvailable; retrying
E1124 12:15:02.735282       1 scheduler.go:627] error selecting node for pod: rejected by "coscheduling" at prefilter: less than minAvailable
E1124 12:15:02.735520       1 factory.go:601] Error scheduling test-ns/tf-work-1-qbtz6: rejected by "coscheduling" at prefilter: less than minAvailable; retrying
E1124 12:15:02.735564       1 scheduler.go:627] error selecting node for pod: rejected by "coscheduling" at prefilter: less than minAvailable
E1124 12:15:24.119796       1 factory.go:601] Error scheduling test-ns/tf-work-2-9t8jg: pod "tf-work-2-9t8jg" rejected while waiting at permit: rejected due to timeout after waiting 10s at plugin coscheduling; retrying
E1124 12:15:34.124308       1 factory.go:601] Error scheduling test-ns/tf-work-2-9t8jg: pod "tf-work-2-9t8jg" rejected while waiting at permit: rejected due to timeout after waiting 10s at plugin coscheduling; retrying
E1124 12:16:39.419128       1 factory.go:601] Error scheduling test-ns/tf-work-1-qbtz6: pod "tf-work-1-qbtz6" rejected while waiting at permit: rejected due to timeout after waiting 10s at plugin coscheduling; retrying
`

**Comment by denkensk** [comment]
preFilter is enhanced feature to reduce the overall scheduling time for the whole group. It will check the total number of pods belonging to the same PodGroup. If the total number is less than minAvailable, the pod will reject in preFilter, then the scheduling cycle will interrupt. And the preFilter is user selectable according to the actual situation of users. If the minAvailable of PodGroup is relatively small, for example less than 5, you can disable this plugin. But if the minAvailable of PodGroup is relatively large, please enable this plugin to reduce the overall scheduling time.

So You can try to disable the prefilter to solve this problem.

**Comment by denkensk** [comment]
And It is recommended to add your cluster information

**Comment by liiitleboy** [comment]
> preFilter is enhanced feature to reduce the overall scheduling time for the whole group. It will check the total number of pods belonging to the same PodGroup. If the total number is less than minAvailable, the pod will reject in preFilter, then the scheduling cycle will interrupt. And the preFilter is user selectable according to the actual situation of users. If the minAvailable of PodGroup is relatively small, for example less than 5, you can disable this plugin. But if the minAvailable of PodGroup is relatively large, please enable this plugin to reduce the overall scheduling time.
> 
> So You can try to disable the prefilter to solve this problem.

thanks,how can I disable the prefilter?
K8S 1.18
请问这玩意怎么禁用，集群信息是指什么

**Comment by denkensk** [comment]
Replace config like this
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
        - name: Coscheduling
      disabled:
        - name: "*"
    permit:
      enabled:
        - name: Coscheduling
    reserve:
      enabled:
        - name: Coscheduling
    postBind:
      enabled:
        - name: Coscheduling
```

**Comment by denkensk** [comment]
Update for 1.18

```yaml
apiVersion: kubescheduler.config.k8s.io/v1alpha2
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "REPLACE_ME_WITH_KUBE_CONFIG_PATH"
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
        - name: Coscheduling
      disabled:
        - name: "*"
    preFilter:
      enabled:
        - name: Coscheduling
    permit:
      enabled:
        - name: Coscheduling
    unreserve:
      enabled:
        - name: Coscheduling
```
