### ISSUE TITLE
The Pod of kube-scheduler : "found unknown field: unreserve"

### ISSUE THREAD

**Issue by kiragoo** [kubernetes-sigs/scheduler-plugins#168]
Hi,all.
Recently,according to the docs:[release-1.19/install.md](https://github.com/kubernetes-sigs/scheduler-plugins/blob/release-1.19/doc/install.md)

The version of k8s cluster: v1.19.8

The container image version is v0.19.8 which was built by myself on making  release-image.amd64 according to [release-1.19/Makefile](https://github.com/kubernetes-sigs/scheduler-plugins/blob/release-1.19/Makefile)

The logs output like this:
```
[root@dev ~]# kubectl logs -f   kube-scheduler-dev -n kube-system
I0330 07:48:34.678869       1 registry.go:173] Registering SelectorSpread plugin
I0330 07:48:34.678915       1 registry.go:173] Registering SelectorSpread plugin
I0330 07:48:35.312023       1 serving.go:331] Generated self-signed cert in-memory
strict decoder error for apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
    unreserve:
      enabled:
      - name: Coscheduling
  pluginConfig:
  - name: Coscheduling
    args:
      kubeConfigPath: /etc/kubernetes/scheduler.conf: v1beta1.KubeSchedulerConfiguration.Profiles: []v1beta1.KubeSchedulerProfile: v1beta1.KubeSchedulerProfile.Plugins: v1beta1.Plugins.ReadObject: found unknown field: unreserve, error found in #10 byte of ...|unreserve":{"enabled|..., bigger context ...|],"enabled":[{"name":"Coscheduling"}]},"unreserve":{"enabled":[{"name":"Coscheduling"}]}},"scheduler|...
```

Here are my yaml files:
- /etc/kubernetes/manifests/kube-scheduler.yaml
```apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
    # <-- the point modified 
    - --config=/etc/kubernetes/scheduler-plugins/sched-cc.yaml
    # -->
    - --port=0
    image: kirago/kube-scheduler:v0.19.8
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    # <-- the point modified 
    - mountPath: /etc/kubernetes/scheduler-plugins/sched-cc.yaml
      name: sched-cc
      readOnly: true
    # <-- the point modified 
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
    # <-- the point modified 
  - hostPath:
      path: /etc/kubernetes/scheduler-plugins/sched-cc.yaml
      type: FileOrCreate
    name: sched-cc
    # <-- the point modified 
status: {}
```
- /etc/kubernetes/scheduler-plugins/sched-crd.yaml
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
    unreserve:
      enabled:
      - name: Coscheduling
  pluginConfig:
  - name: Coscheduling
    args:
      kubeConfigPath: /etc/kubernetes/scheduler.conf
```
 - /etc/kubernetes/scheduler-plugins/all-in-one.yaml
 ```
# First part
# Apply extra privileges to system:kube-scheduler.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-scheduler:plugins
rules:
- apiGroups: ["scheduling.sigs.k8s.io"]
  resources: ["podgroups", "elasticquotas"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-scheduler:plugins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler:plugins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
---
# Second part
# Install the controller image.
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-plugins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-plugins-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["scheduling.sigs.k8s.io"]
  resources: ["podgroups", "elasticquotas"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-plugins-controller
subjects:
- kind: ServiceAccount
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
roleRef:
  kind: ClusterRole
  name: scheduler-plugins-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
  labels:
    app: scheduler-plugins-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-plugins-controller
  template:
    metadata:
      labels:
        app: scheduler-plugins-controller
    spec:
      serviceAccount: scheduler-plugins-controller
      containers:
      - name: scheduler-plugins-controller
        image: kirago/controller:v0.19.8
```
- /etc/kubernetes/scheduler-plugins/coschduling-crd.yaml
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.sigs.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes-sigs/scheduler-plugins/pull/50"
spec:
  group: scheduling.sigs.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
    singular: podgroup
    shortNames:
    - pg
    - pgs
  scope: Namespaced
  versions:
  - name: "v1alpha1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              minMember:
                type: integer
                minimum: 1
              scheduleTimeoutSeconds:
                type: integer
              minResources:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
              occupiedBy:
                type: string
              scheduled:
                type: integer
              running:
                type: integer
              succeeded:
                type: integer
              failed:
                type: integer
              scheduleStartTime:
                type: string
                format: date-time
```
I'll appreciate your help☺️

**Comment by kiragoo** [comment]
According to the error info
 `     kubeConfigPath: /etc/kubernetes/scheduler.conf: v1beta1.KubeSchedulerConfiguration.Profiles: []v1beta1.KubeSchedulerProfile: v1beta1.KubeSchedulerProfile.Plugins: v1beta1.Plugins.ReadObject: found unknown field: unreserve, error found in #10 byte of ...|unreserve":{"enabled|..., bigger context ...|],"enabled":[{"name":"Coscheduling"}]},"unreserve":{"enabled":[{"name":"Coscheduling"}]}},"scheduler|...`
Maybe it can't parse the "unreverse" in "coscheduling" plugin,the i tried to annotated the part of  "plugins.unresrve"
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
    # unreserve:
    #   enabled:
    #   - name: Coscheduling
  pluginConfig:
  - name: Coscheduling
    args:
      kubeConfigPath: /etc/kubernetes/scheduler.conf
```
then deploy  PodGroup: pg1 and Deployment:pg1 to verify.
As expected, the kube-scheduler pod worked as well and the status of pg1.
