### ISSUE TITLE
RunContainerError for local image

### ISSUE THREAD

**Issue by tfy15jst** [kubernetes-sigs/scheduler-plugins#169]
Hi!
I have been trying to make the scheduler use your image after building it locally, in order to try to modify it later on.
But i have run into a problem.
Following your [tutorial](https://github.com/kubernetes-sigs/scheduler-plugins/blob/master/doc/install.md) worked fine.
But when i try to make it use the local image instead of _k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.19.8_, i get a RunContainerError.

This is the output from _kubectl describe pods -n kube-system kube-scheduler-minikube_

```
Events:
  Type     Reason   Age                From               Message
  ----     ------   ----               ----               -------
  Warning  Failed   36s                kubelet, minikube  Error: open /var/lib/kubelet/pods/f6bc0188210d22f54cd16a960ebbea41/etc-hosts: no such file or directory
  Normal   Pulled   15s (x4 over 36s)  kubelet, minikube  Container image "docker.io/johansundkvist/schedulerconfig:scheduler3" already present on machine
  Normal   Created  14s (x3 over 35s)  kubelet, minikube  Created container kube-scheduler
  Warning  Failed   13s (x3 over 34s)  kubelet, minikube  Error: failed to start container "kube-scheduler": Error response from daemon: OCI runtime create failed: container_linux.go:370: starting container process caused: exec: "kube-scheduler": executable file not found in $PATH: unknown
  Warning  BackOff  5s (x4 over 25s)   kubelet, minikube  Back-off restarting failed container
```

I assume the main problem is the failure regarding "kube-scheduler" not being in $PATH. 
As previously stated this does not appear when pulling the image from _k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.19.8_.
Have i done somethin wrong when building the image or is there something i have missed?

Here are my yaml files.

- _/etc/kubernetes/manifests/kube-scheduler.yaml_
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler
  namespace: kube-system
spec:
  containers:
  - command:
    - kube-scheduler
    - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
    - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
    - --bind-address=127.0.0.1
      #- --config=/etc/kubernetes/sched-cc.yaml
    - --kubeconfig=/etc/kubernetes/scheduler.conf
    - --leader-elect=false
    - --port=0
    #image: k8s.gcr.io/kube-scheduler:v1.20.2
    image: docker.io/<DOCKERHUBUSER>/schedulerconfig:scheduler
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 8
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    name: kube-scheduler
    resources:
      requests:
        cpu: 100m
    startupProbe:
      failureThreshold: 24
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 10259
        scheme: HTTPS
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 15
    volumeMounts:
    - mountPath: /etc/kubernetes/scheduler.conf
      name: kubeconfig
      readOnly: true
    - mountPath: /etc/kubernetes/sched-cc.yaml
      name: sched-cc
      readOnly: true
  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/scheduler.conf
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /etc/kubernetes/sched-cc.yaml
      type: FileOrCreate
    name: sched-cc
status: {}
```
- _/etc/kubernetes/scheduler-plugins/sched-crd.yaml_ 
```
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  # (Optional) Change true to false if you are not running a HA control-plane.
  leaderElect: false
clientConnection:
  kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
  #  unreserve:
  #    enabled:
  #    - name: Coscheduling
  # pluginConfig is needed for coscheduling plugin to manipulate PodGroup CR objects.
  pluginConfig:
  - name: Coscheduling
    args:
      kubeConfigPath: /etc/kubernetes/scheduler.conf
```
Unreserve is commented out as it cannot be found for presumably an unrelated reason.
Possibly the same problem mentioned in issue #168.

I would be grateful for any kind of help! :)
