### ISSUE TITLE
Can I use this plugin in gke?

### ISSUE THREAD

**Issue by fuine6** [kubernetes-sigs/scheduler-plugins#188]
I use Google Kubernetes Engine.

In the second step of the [documentation](https://github.com/kubernetes-sigs/scheduler-plugins/blob/release-1.19/doc/install.md#install-release-v0198-and-use-coscheduling).

I cannot find **/etc/kubernetes/manifests/kube-scheduler.yaml** in gke.

It has only one file here.
```
$ ls /etc/kubernetes/manifests/
...
kube-proxy.manifest
```
```
$ cat /etc/kubernetes/manifests/kube-proxy.manifest
...
spec:
  priorityClassName: system-node-critical
  priority: 2000001000
  hostNetwork: true
  tolerations:
  - operator: "Exists"
    effect: "NoExecute"
  - operator: "Exists"
    effect: "NoSchedule"
  containers:
  - name: kube-proxy
    image: gke.gcr.io/kube-proxy-amd64:v1.19.8-gke.2000
    resources:
      requests:
        cpu: 100m
    command:
    - /bin/sh
    - -c
    - exec kube-proxy --master=https://35.229.254.32 --kubeconfig=/var/lib/kube-proxy/kubeconfig --cluster-cidr=10.92.0.0/14 --oom-score-adj=-998 --v=2 --feature-gates=DynamicKubeletConfig=false,RotateKubeletServerCertificate=true --iptables-sync-period=1m --iptables-min-sync-period=10s --ipvs-sync-period=1m --ipvs-min-sync-period=10s --detect-local-mode=NodeCIDR 1>>/var/log/kube-proxy.log 2>&1
    
    
      
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /etc/ssl/certs
      name: etc-ssl-certs
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usr-ca-certs
      readOnly: true
    - mountPath: /var/log
      name: varlog
      readOnly: false
    - mountPath: /var/lib/kube-proxy/kubeconfig
      name: kubeconfig
      readOnly: false
    - mountPath: /run/xtables.lock
      name: iptableslock
      readOnly: false
    - mountPath: /lib/modules
      name: lib-modules
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/ca-certificates
    name: usr-ca-certs
  - hostPath:
      path: /etc/ssl/certs
    name: etc-ssl-certs
  - hostPath:
      path: /var/lib/kube-proxy/kubeconfig
      type: FileOrCreate
    name: kubeconfig
  - hostPath:
      path: /var/log
    name: varlog
  - hostPath:
      path: /run/xtables.lock
      type: FileOrCreate
    name: iptableslock
  - name: lib-modules
    hostPath:
      path: /lib/modules
```

Client Version: v1.20.5
Server Version: v1.19.8-gke.2000

**Comment by Huang-Wei** [comment]
I guess you don't have privileges accessing the control plane of GKE.

@alculquicondor @ahg-g is there any extension a user can leverage to plumb in scheduler plugins?

**Comment by alculquicondor** [comment]
You can only use plugins if you run a second scheduler in your nodes https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/

**Comment by fuine6** [comment]
I have tried [multiple schedulers](https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/) and it works fine.

I am not sure how to use this plugin as a scheduler.

This is what I tried on gke, it seems to work, but I am not sure if I am using it correctly. I have some questions, this is my configuration.

### 1. Create scheduler-config.yaml
```yaml
apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
#clientConnection:
  #kubeconfig: /etc/kubernetes/scheduler.conf
profiles:
- schedulerName: coscheduling-scheduler
  plugins:
    queueSort:
      enabled:
      - name: Coscheduling
      disabled:
      - name: "*"
    preFilter:
      enabled:
      - name: Coscheduling
    permit:
      enabled:
      - name: Coscheduling
    reserve:
      enabled:
      - name: Coscheduling
    postBind:
      enabled:
      - name: Coscheduling
```

### 2. Create dockerfile
```dockerfile
FROM k8s.gcr.io/scheduler-plugins/kube-scheduler:v0.19.9
ADD scheduler-config.yaml /plugin/scheduler-config.yaml
```

### 3. Build and push docker image
```
docker build -t gcr.io/myproject/coscheduling-scheduler:1.0 .
docker push gcr.io/myproject/coscheduling-scheduler:1.0
```

### 4. kubectl apply -f crd.yaml
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podgroups.scheduling.sigs.k8s.io
  annotations:
    "api-approved.kubernetes.io": "https://github.com/kubernetes-sigs/scheduler-plugins/pull/50"
spec:
  group: scheduling.sigs.k8s.io
  names:
    kind: PodGroup
    plural: podgroups
    singular: podgroup
    shortNames:
    - pg
    - pgs
  scope: Namespaced
  versions:
  - name: "v1alpha1"
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              minMember:
                type: integer
                minimum: 1
              scheduleTimeoutSeconds:
                type: integer
              minResources:
                type: object
                additionalProperties:
                  type: string
          status:
            type: object
            properties:
              phase:
                type: string
              occupiedBy:
                type: string
              scheduled:
                type: integer
                default: 0
              running:
                type: integer
                default: 0
              succeeded:
                type: integer
                default: 0
              failed:
                type: integer
                default: 0
              scheduleStartTime:
                type: string
                format: date-time
```

### 5. kubectl apply -f all-in-one.yaml
```yaml
# First part
# Apply extra privileges to system:kube-scheduler.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-scheduler:plugins
rules:
- apiGroups: ["scheduling.sigs.k8s.io"]
  resources: ["podgroups", "elasticquotas"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: system:kube-scheduler:plugins
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler:plugins
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: system:kube-scheduler
---
# Second part
# Install the controller image.
apiVersion: v1
kind: Namespace
metadata:
  name: scheduler-plugins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-plugins-controller
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["scheduling.sigs.k8s.io"]
  resources: ["podgroups", "elasticquotas"]
  verbs: ["get", "list", "watch", "create", "delete", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scheduler-plugins-controller
subjects:
- kind: ServiceAccount
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
roleRef:
  kind: ClusterRole
  name: scheduler-plugins-controller
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: scheduler-plugins-controller
  namespace: scheduler-plugins
  labels:
    app: scheduler-plugins-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler-plugins-controller
  template:
    metadata:
      labels:
        app: scheduler-plugins-controller
    spec:
      serviceAccount: scheduler-plugins-controller
      containers:
      - name: scheduler-plugins-controller
        image: k8s.gcr.io/scheduler-plugins/controller:v0.19.9
        imagePullPolicy: IfNotPresent
```

### 6. kubectl apply -f coscheduling-scheduler.yaml
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coscheduling-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coscheduling-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: coscheduling-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coscheduling-scheduler-as-volume-scheduler
subjects:
- kind: ServiceAccount
  name: coscheduling-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:volume-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: coscheduling-scheduler-as-extension-apiserver-authentication-reader
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: coscheduling-scheduler
  namespace: kube-system
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coscheduling-scheduler-as-system:kube-scheduler:plugins
subjects:
- kind: ServiceAccount
  name: coscheduling-scheduler
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler:plugins
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: coscheduling-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
    spec:
      serviceAccountName: coscheduling-scheduler
      containers:
      - command:
        - /bin/kube-scheduler
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=coscheduling-scheduler
        - --config=/plugin/scheduler-config.yaml
        image: gcr.io/myproject/coscheduling-scheduler:1.0
        name: coscheduling-scheduler
        resources:
          requests:
            cpu: '0.1'
        securityContext:
          privileged: false
        volumeMounts: []
      hostNetwork: false
      hostPID: false
      volumes: []
```

### 7. kubectl apply -f podgroup.yaml
```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: pg1
spec:
  scheduleTimeoutSeconds: 120
  minMember: 3
```

### 8. kubectl apply -f test-deploy.yaml
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
        pod-group.scheduling.sigs.k8s.io: pg1
    spec:
      schedulerName: coscheduling-scheduler
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.2
```

I have some questions.
1. In step 1, gke does not have /etc/kubernetes/scheduler.conf, I ignore kubeconfig, Is this correct?
2. Do I need all-in-one.yaml? It seems to work without it.
3. In step 7, If I set scheduleTimeoutSeconds to 10, I see timeout error even if replicas is greater than or equal to minMember, in this case I expect the schedule to be fast

I hope there is documentation for this plugin as a second scheduler, or can I use helm to install this plugin?

```
Client Version: v1.20.5
Server Version: v1.19.9-gke.700
```
