### ISSUE TITLE
How to get KubeSchedulerConfiguration in your plugin?

### ISSUE THREAD

**Issue by shenkonghui** [kubernetes-sigs/scheduler-plugins#231]
I wirte a plugin and add a crd. I need kubeconfig to generate restConfig. But I can not found how to import kubeconfig in KubeSchedulerConfiguration?  how to get it?

**Comment by lianghao208** [comment]
This configuration might help:
```
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: KubeSchedulerConfiguration
      leaderElection:
        leaderElect: false
      clientConnection:
        # import your kubeconfig file path
        kubeconfig: "/etc/kubernetes/scheduler.conf"
      profiles:
        - schedulerName: <Your Scheduler Name>
          plugins:
            filter:
              enabled:
                - name: <Your Plugin Name>
          # optional plugin configs
          pluginConfig:
          - name: <Your Plugin Name>
            args:
              # import your kubeconfig file path
              kubeconfigpath: "/etc/kubernetes/scheduler.conf"
              namespaces:
              - "test-namespace"
```

**Comment by shenkonghui** [comment]
@lianghao208 Thank you for replying to me, but I want to know how to get it in the code

**Comment by lianghao208** [comment]
I think you need to add optional plugin config in KubeSchedulerConfiguration
```
      apiVersion: kubescheduler.config.k8s.io/v1beta1
      kind: KubeSchedulerConfiguration
      leaderElection:
        leaderElect: false
      clientConnection:
        # import your kubeconfig file path
        kubeconfig: "/etc/kubernetes/scheduler.conf"
      profiles:
        - schedulerName: <Your Scheduler Name>
          plugins:
            filter:
              enabled:
                - name: <Your Plugin Name>
          # optional plugin configs
          pluginConfig:
          - name: <Your Plugin Name>
            args:
              kubeconfigpath: "/etc/kubernetes/scheduler.conf"
              namespaces:
              - "test-namespace"
```

the args `kubeconfigpath` can import the kubeconfig for your plugin.
For codes:
```
import "k8s.io/client-go/tools/clientcmd"

conf, err := clientcmd.BuildConfigFromFlags(args.KubeMaster, args.KubeConfigPath)
```
