### ISSUE TITLE
Update coscheduling Readme.md with postFilter

### ISSUE THREAD

**Issue by mateuszlitwin** [kubernetes-sigs/scheduler-plugins#244]
After postFilter was added in https://github.com/kubernetes-sigs/scheduler-plugins/pull/126 docs should be updated accordingly.

```
postFilter:
  enabled:
  - name: "DefaultPreemption"
  - name: "Coscheduling" 
```
