### ISSUE TITLE
Noderesourcetopology plugin disqualifies pods that request memory

### ISSUE THREAD

**Issue by Tal-or** [kubernetes-sigs/scheduler-plugins#249]
**What happened:**
I'm trying to deploy a pod that requests some memory and has a guaranteed Qos, using the noderesourcetopology plugin.
```
kind: Pod
...
  schedulerName: topo-aware-scheduler
  resources:
       limits:
         memory: "100Mi"
         cpu: "1"
       requests:
         memory: "100Mi"
         cpu: "1"
```
Although there are nodes in the cluster that are able to address the pod's request, the pod is getting qualified.

**What you expected to happen:**
The pod should be admitted by the scheduler plugin.

**How to reproduce it (as minimally and precisely as possible):**
1. On a Kind cluster, deploy the scheduler-plugin using the installation instruction from here: https://github.com/killianmuldoon/documentation/tree/installguide/install-guides 
2. Create a pod with the spec as described above

**Why it happened?:**
NFD, which is the resource-exporter component for the scheduler plugin, doesn't hold information about memory distribution between NUMA zones.

On the other hand, the noderesourcetopology plugin is looking for the memory information in order to decide if the node can address the pod's request.

When noderesourcetopology plugin queries NFD for memory information (which NFD doesn't have) it disqualified the node.
The same happens for all nodes, thus no pod which asks for memory can be deployed.

**How it can be resolved?**
NFD should provide the memory information.
The memory information already exported by the PodreasourceAPI: https://github.com/kubernetes/kubernetes/pull/101030 
Once NFD will have the ability to account for the memory resources, we should update the plugin to work with the fixed NFD version and the issue will get resolved.
