### ISSUE TITLE
coscheduling: podGroup.status.scheduler always growing? Does it need to be reconciled？

### ISSUE THREAD

**Issue by NoicFank** [kubernetes-sigs/scheduler-plugins#361]
currently, there is one place to edit `status.scheduler` as follows:
[code](https://github.com/kubernetes-sigs/scheduler-plugins/blob/277b6bdec18f8a9e9ccd1bfeaf4b66495bfc6f92/pkg/coscheduling/core/core.go#L227)
```go
pgCopy.Status.Scheduled++
```

which leads to some problems, like the example as follow:
-  10 pod are running with pg:
```
spec:
  minMember: 8
status:
  phase: Running
  running: 10
  scheduled: 10
```
- then, 5 pods are evicted, where they need to be re-scheduled. Then, I expected podGroup will be reconciled to:
```
spec:
  minMember: 8
status:
  phase: Pending
  running: 5
  scheduled: 5
```
- which will guarantee those 5 pod to be scheduled together. then, finally
```
spec:
  minMember: 8
status:
  phase: Running
  running: 10
  scheduled: 10
```
- but currently, its
```
spec:
  minMember: 8
status:
  phase: Running
  running: 5
  scheduled: 10 (15)
```
