### ISSUE TITLE
noderesourcetopology: wrong accounting of the filter plugin when scope=container

### ISSUE THREAD

**Issue by Tal-or** [kubernetes-sigs/scheduler-plugins#366]
**Problem Description:**

When **scope=container** and the scheduled pod has **multiple containers**, the noderesourcetopology filter plugin does the accounting in a wrong way.
The plugin treats each container inside the pod individually, and check if it's fit into the (NUMA) node without taking into consideration the resources which already allocated by the previous container's requests.

**Example:**

 A guaranteed pod:
```yaml
Pod:
  Scheduler-Name: topo-aware-scheduler
  Container A:
    CPUs: 2
    Memory: 100M
  Container B:
    CPUs: 2
    Memory: 100M
```
A node candidate for scheduling: 
```yaml
Node:
 NUMA Zone 1:
  Available:
   CPUs: 2
   Memory: 100M
 NUMA Zone 2: 
  Available:
   CPUs: 1
   Memory: 50M
```
The filter plugin iterate over the containers in the pod:
It finds that ```NUMA Zone 1``` is a good fit for ```Container A```.
Next it looks at ```Container B```'s resource request and finds that it fits for ```NUMA Zone 1``` as well and then mark the Node as a possible candidate. 
This is wrong because the available resources under ```NUMA Zone 1``` are **already taken** by ```Container A``` and cannot suffice ```Container B```'s resource request too.

**Comment by Huang-Wei** [comment]
I think this is a valid concern. Furthermore, we may need to make the filtering logic a bit smarter, like by giving the available node as:

```yaml
Node:
 NUMA Zone 1:
  Available:
   CPUs: 2
   Memory: 100M
 NUMA Zone 2: 
  Available:
   CPUs: 1
   Memory: 50M
```

And the incoming pod's containers are like:

```yaml
Pod:
  Scheduler-Name: topo-aware-scheduler
  Container A:
    CPUs: 1
    Memory: 50M
  Container B:
    CPUs: 2
    Memory: 100M
```

We should fit container A to numa 2; otherwise (fit it to numa 1) container B would be falsely claimed as unschedulable.

cc @swatisehgal @fromanirh
