### ISSUE TITLE
[CapacityScheduling] ElasticQuota default value for "max" is zero

### ISSUE THREAD

**Issue by Telemaco019** [kubernetes-sigs/scheduler-plugins#424]
Hello everyone,

When creating an `ElasticQuota` resource, if the "max" field is not provided then its default value is zero. Is this the intended behavior? Quoting [KEP 9 - Capacity Scheduling](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/kep/9-capacity-scheduling): "_Max is infinite by default, min is 0 by default_", so I was expecting the plugin to threat the max field as "infinite" when the custom resource does not specify it.

Having the max field with "infinite" as the default value would be helpful in those cases where someone needs to define just the minimum resources that need to be guaranteed to a namespace, without specifying any upper limit constraint. In such a case, I would like to create the `ElasticQuota` resource as follows, without specifying any value for the max field:

```yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: quota1
  namespace: quota1
spec:
   min:
    cpu: 4
```

https://github.com/kubernetes-sigs/scheduler-plugins/issues/424#tasklist-block-5282e773-1998-444a-8604-324ddd2a1d32

**Comment by Gekko0114** [comment]
I agree with this issue.

When I create ElasticQuota like this,
```
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: ElasticQuota
metadata:
  name: test
  namespace: test
spec:
  max:
    cpu: 10
    nvidia.com/gpu: 1
```
and create pod having this resource,

```
cpu: 10
memory: 1
nvidia.com/gpu: 1
```
then max of this ElasticQuota is calculated like this(same as min).
```
spec:
  max:
    cpu: 10
    memory: 0
    nvidia.com/gpu: 1
```

I guess this is unintended behavior.
Can I fix this issue?
