### ISSUE TITLE
How can I apply the plugins  on my  own kubernetes machine installed by Kubeadm

### ISSUE THREAD

**Issue by Wenshiqi222** [kubernetes-sigs/scheduler-plugins#44]
Recently，I  plan to design my own kube-scheduler，considering that kubernetes-sigs has already designed the scheduler-plugins based on the Framework extention points，so i just wanna try the qos plugins given by the sigs. When applying the plugins，i havd another question：Since my kubernetes environment isn‘t applyed by “Make” the source code，but by the Kubeadm，all my components are running in containers. 
Does that mean i should “Make" the plugins firstly ，then make it  a image running by the Pod？ Shoud the Pod be applied on the Master Machine or the Worker Node？

**Comment by xq2005** [comment]
Hi @Wenshiqi222 , some experience from me.
1. Build you plugin project and generate a new scheduler.
2. Build a new docker image with new scheduler.
3. Follow https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler to run new scheduler as a second scheduler
4. Test new scheduler
5. When new scheduler is stable, replace the default scheduler image by the new image.

**Comment by Wenshiqi222** [comment]
> Hi @Wenshiqi222 , some experience from me.
> 
> 1. Build you plugin project and generate a new scheduler.
> 2. Build a new docker image with new scheduler.
> 3. Follow https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/#define-a-kubernetes-deployment-for-the-scheduler to run new scheduler as a second scheduler
> 4. Test new scheduler
> 5. When new scheduler is stable, replace the default scheduler image by the new image.

Yes,i got it and did step by step, but when i try step 3 to run my own scheduler,i had a problem about the config path.Here is my
schedulerPod yaml file:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-kube-scheduler
subjects:
- kind: ServiceAccount
  name: my-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:kube-scheduler
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-config
  namespace: kube-system
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1alpha2
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
    clientConnection:
      kubeconfig: "/etc/kubernetes/scheduler.conf"
    profiles:
    - schedulerName: my-scheduler1
      plugins:
        queueSort:
          enabled:
          - name: QOSSort
          disabled:
          - name: "*"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: my-scheduler1
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: first
    spec:
      serviceAccountName: my-scheduler     
      volumes:
      - name: scheduler-config
        configMap:
          name: scheduler-config
      containers:
      - args:
        - --config=scheduler/scheduler-config.yaml
        image: wenshiqi/my-kube-scheduler:2.0
        imagePullPolicy: IfNotPresent
       # livenessProbe:
       #   httpGet:
       #     path: /healthz
       #     port: 10251
       #   initialDelaySeconds: 15
        name: kube-second-scheduler
       # readinessProbe:
       #   httpGet:
       #     path: /healthz
       #     port: 10251
        resources:
          requests:
            cpu: '50m'      
        volumeMounts: 
        - name: scheduler-config
          mountPath: /scheduler

```

and here is my Dockerfile 

```
FROM debian:stretch-slim
ADD ./bin/kube-scheduler /usr/local/bin/kube-scheduler

CMD ["kube-scheduler"]
```

since i should run my own scheduler with the command "--config=.....",so i need to wirte the args in the yaml file,and i copy the configfile i needed into the ConfigMap, whcih the  pod volume will be attached ,
But when i try to start the container, i had a CrashLoopBackOff status on the SchedulerPod, and the logs show 

```
 Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned kube-system/my-scheduler1-67fdd4bc97-4c65t to node01
  Normal   Pulled     30m (x5 over 32m)     kubelet, node01    Container image "wenshiqi/my-kube-scheduler:2.0" already present on machine
  Normal   Created    30m (x5 over 32m)     kubelet, node01    Created container kube-second-scheduler
  **Warning  Failed     30m (x5 over 32m)     kubelet, node01    Error: failed to start container "kube-second-scheduler": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--config=scheduler/scheduler-config.yaml\": stat --config=scheduler/scheduler-config.yaml: no such file or directory": unknown
  Warning  BackOff    2m6s (x138 over 31m)  kubelet, node01    Back-off restarting failed container**
```
i 've already copy  the  shceduler-config.yaml  into the configMap, why  the docker daemon  still cannot find the file?

**Comment by denkensk** [comment]
Hi You can execute `make local_image` to  build image. Use the new image in scheduler.yaml to try again. @Wenshiqi222

**Comment by denkensk** [comment]
```
      containers:
      - args:
        - --config=scheduler/scheduler-config.yaml
```
The path of config is `/scheduler/scheduler-config.yaml`.

**Comment by yuchen-sun** [comment]
@denkensk Hi，in my cluster，coscheduling do not work。how to fix it？
I set the configuration and run the nginx example,but nginx pod group do not Pending when the  gpu resource does not meet the miniAvaible.
![image](https://user-images.githubusercontent.com/37729051/91538113-deea4180-e949-11ea-815d-7e1f1d62883b.png)

**Comment by Wenshiqi222** [comment]
> ```
>       containers:
>       - args:
>         - --config=scheduler/scheduler-config.yaml
> ```
> 
> The path of config is `/scheduler/scheduler-config.yaml`.

Still got the same warnning 😄
`Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--config=/scheduler/scheduler-config.yaml\": stat --config=/scheduler/scheduler-config.yaml: no such file or directory": unknown`

**Comment by Wenshiqi222** [comment]
> Hi You can execute `make local_image` to build image. Use the new image in scheduler.yaml to try again. @Wenshiqi222

hi，I am a new learner in kubernentes and docker ,what do u mean by "make local_image",is the probelm in the image?

**Comment by yuchen-sun** [comment]
> > ```
> >       containers:
> >       - args:
> >         - --config=scheduler/scheduler-config.yaml
> > ```
> > 
> > 
> > The path of config is `/scheduler/scheduler-config.yaml`.
> 
> Still got the same warnning 😄
> `Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--config=/scheduler/scheduler-config.yaml\": stat --config=/scheduler/scheduler-config.yaml: no such file or directory": unknown`

I think the path of config is `/scheduler/scheduler-config/<configmap.data.name>`
if you use --from-file flag when creating configmap, you can use `/scheduler/scheduler-config/<filename>`

**Comment by denkensk** [comment]
@Wenshiqi222  You can change it like this and delete the args. 
```
  containers:
  - command:
    - kube-scheduler
    - --config=scheduler/scheduler-config.yaml
```

**Comment by denkensk** [comment]
@yuchen-sun  Can you show me your scheduler-conf.yaml and nginx.yaml ?

**Comment by yuchen-sun** [comment]
> @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?

the same as  [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
By the way ，I add the plugin to Kubernetes and run  `make kube-scheduler` to build a  new scheduler.
Is there a problem with this approach？

**Comment by denkensk** [comment]
> > @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?
> 
> the same as [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
> By the way ，I add the plugin to Kubernetes and run `make kube-scheduler` to build a new scheduler.
> Is there a problem with this approach？

Have your register the plugin in registry？

**Comment by yuchen-sun** [comment]
> > > @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?
> > 
> > 
> > the same as [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
> > By the way ，I add the plugin to Kubernetes and run `make kube-scheduler` to build a new scheduler.
> > Is there a problem with this approach？
> 
> Have your registered the plugin in registry？

Yes,I've changed the following (If not ,I will get an error that the plugin cannot be found)
```
1. algorithmprovider/registry 
2. framework/registry
```
Anything missing？

**Comment by denkensk** [comment]
> > > > @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?
> > > 
> > > 
> > > the same as [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
> > > By the way ，I add the plugin to Kubernetes and run `make kube-scheduler` to build a new scheduler.
> > > Is there a problem with this approach？
> > 
> > 
> > Have your registered the plugin in registry？
> 
> Yes,I've changed the following (If not ,I will get an error that the plugin cannot be found)
> 
> ```
> 1. algorithmprovider/registry 
> 2. framework/registry
> ```
> 
> Anything missing？

I think it’s enough. Do you find the info of Coscheduling in log?

**Comment by yuchen-sun** [comment]
> > > > > @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?
> > > > 
> > > > 
> > > > the same as [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
> > > > By the way ，I add the plugin to Kubernetes and run `make kube-scheduler` to build a new scheduler.
> > > > Is there a problem with this approach？
> > > 
> > > 
> > > Have your registered the plugin in registry？
> > 
> > 
> > Yes,I've changed the following (If not ,I will get an error that the plugin cannot be found)
> > ```
> > 1. algorithmprovider/registry 
> > 2. framework/registry
> > ```
> > 
> > 
> > Anything missing？
> 
> I think it’s enough. Do you find the info of Coscheduling in log?

No.In the logs, there is no information about the PodGroup.

**Comment by Wenshiqi222** [comment]
> @Wenshiqi222 You can change it like this and delete the args.
> 
> ```
>   containers:
>   - command:
>     - kube-scheduler
>     - --config=/scheduler/scheduler-config.yaml
> ```

Thanks ,it doesn't warn the path problem,but the scheduler container cannot run normally,which shows:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned kube-system/my-scheduler1-7f7ffb7f5f-mt726 to node01
  Normal   Pulled     78s (x5 over 5m1s)    kubelet, node01    Container image "wenshiqi/my-kube-scheduler:2.0" already present on machine
  Normal   Created    78s (x5 over 5m1s)    kubelet, node01    Created container kube-second-scheduler
  Normal   Started    78s (x5 over 5m1s)    kubelet, node01    Started container kube-second-scheduler
  Warning  BackOff    21s (x10 over 3m57s)  kubelet, node01    Back-off restarting failed container
```
Where is the problem?  Is it possible that i didn't wirte the command "--kubeconfig?" to send permission messege to API Server? But i've already wite the kubeconfig"scheduler.conf" PATH in the sheduler-config.yaml :
```
    clientConnection:
      kubeconfig: "/etc/kubernetes/scheduler.conf"
```
i was wondering since the container volumeMount is the configMap, the PATH  "/etc/kubernetes/scheduler.conf" can be tell by the K8s？Or is this the reason why my container is Back-off？
Really thanks

**Comment by Wenshiqi222** [comment]
> > > ```
> > >       containers:
> > >       - args:
> > >         - --config=scheduler/scheduler-config.yaml
> > > ```
> > > 
> > > 
> > > The path of config is `/scheduler/scheduler-config.yaml`.
> > 
> > 
> > Still got the same warnning 😄
> > `Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"--config=/scheduler/scheduler-config.yaml\": stat --config=/scheduler/scheduler-config.yaml: no such file or directory": unknown`
> 
> I think the path of config is `/scheduler/scheduler-config/<configmap.data.name>`
> if you use --from-file flag when creating configmap, you can use `/scheduler/scheduler-config/<filename>`

i will try that ，thanks

**Comment by denkensk** [comment]
> > @Wenshiqi222 You can change it like this and delete the args.
> > ```
> >   containers:
> >   - command:
> >     - kube-scheduler
> >     - --config=/scheduler/scheduler-config.yaml
> > ```
> 
> Thanks ,it doesn't warn the path problem,but the scheduler container cannot run normally,which shows:
> 
> ```
> Events:
>   Type     Reason     Age                   From               Message
>   ----     ------     ----                  ----               -------
>   Normal   Scheduled  <unknown>             default-scheduler  Successfully assigned kube-system/my-scheduler1-7f7ffb7f5f-mt726 to node01
>   Normal   Pulled     78s (x5 over 5m1s)    kubelet, node01    Container image "wenshiqi/my-kube-scheduler:2.0" already present on machine
>   Normal   Created    78s (x5 over 5m1s)    kubelet, node01    Created container kube-second-scheduler
>   Normal   Started    78s (x5 over 5m1s)    kubelet, node01    Started container kube-second-scheduler
>   Warning  BackOff    21s (x10 over 3m57s)  kubelet, node01    Back-off restarting failed container
> ```
> 
> Where is the problem? Is it possible that i didn't wirte the command "--kubeconfig?" to send permission messege to API Server? But i've already wite the kubeconfig"scheduler.conf" PATH in the sheduler-config.yaml :
> 
> ```
>     clientConnection:
>       kubeconfig: "/etc/kubernetes/scheduler.conf"
> ```
> 
> i was wondering since the container volumeMount is the configMap, the PATH "/etc/kubernetes/scheduler.conf" can be tell by the K8s？Or is this the reason why my container is Back-off？
> Really thanks

@Wenshiqi222 
It's better to find the log of the pod.
`Kubectl logs -f -n kube-system podname`
I guess the error is `can find the /etc/kubernetes/scheduler.conf`.

**Comment by denkensk** [comment]
> > > > > > @yuchen-sun Can you show me your scheduler-conf.yaml and nginx.yaml ?
> > > > > 
> > > > > 
> > > > > the same as [readme](https://github.com/kubernetes-sigs/scheduler-plugins/tree/master/pkg/coscheduling)
> > > > > By the way ，I add the plugin to Kubernetes and run `make kube-scheduler` to build a new scheduler.
> > > > > Is there a problem with this approach？
> > > > 
> > > > 
> > > > Have your registered the plugin in registry？
> > > 
> > > 
> > > Yes,I've changed the following (If not ,I will get an error that the plugin cannot be found)
> > > ```
> > > 1. algorithmprovider/registry 
> > > 2. framework/registry
> > > ```
> > > 
> > > 
> > > Anything missing？
> > 
> > 
> > I think it’s enough. Do you find the info of Coscheduling in log?
> 
> No.In the logs, there is no information about the PodGroup.

Can you try the image of this scheduler-plugins to have the control experiment? @yuchen-sun

**Comment by xq2005** [comment]
> i was wondering since the container volumeMount is the configMap, the PATH "/etc/kubernetes/scheduler.conf" can be tell by the K8s？Or is this the reason why my container is Back-off？

@Wenshiqi222
/etc/kubernetes/scheduler.conf (contains auth data ) is used for connecting to k8s api server.  You can use host path volume to mount your master's /etc/kubernetes/ into your scheduler's container.
```yaml
          volumeMounts:
            - name: scheduler-config
              mountPath: /etc/kubernetes
```

**Comment by yuchen-sun** [comment]
I've done it, and it still doesn't work. @denkensk 
Is there anything wrong with my yaml？
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: co-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: co-scheduler-as-kube-scheduler

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:kube-scheduler
subjects:
  - kind: ServiceAccount
    name: co-scheduler
    namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: co-scheduler-volume-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:volume-scheduler
subjects:
  - kind: ServiceAccount
    name: co-scheduler
    namespace: kube-system
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: co-scheduler-config-role-binding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: extension-apiserver-authentication-reader
subjects:
  - kind: ServiceAccount
    name: co-scheduler
    namespace: kube-system
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
    app: co-scheduler
  name: co-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
        version: second
        app: co-scheduler
    spec:
      serviceAccountName: co-scheduler
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
        - command:
            - /usr/local/bin/kube-scheduler
            - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
            - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
            - --address=0.0.0.0
            - --leader-elect=false
            - --scheduler-name=co-scheduler
            - --kubeconfig=/etc/kubernetes/scheduler.conf
            - --config=/etc/kubernetes/scheduler-conf/scheduler-conf.yaml
            - --policy-config-file=/etc/kubernetes/scheduler-score/scheduler-score.json
          image: yuchen-sun/kubernetes/scheduler:v0.0.8
          ports:
            - containerPort: 8000
          livenessProbe:
            httpGet:
              path: /healthz
              port: 10251
            initialDelaySeconds: 15
          name: kube-co-scheduler
          readinessProbe:
            httpGet:
              path: /healthz
              port: 10251
          resources:
            requests:
              cpu: '0.2'
          securityContext:
            privileged: false
          volumeMounts:
            - name: kubeconfig
              mountPath:  /etc/kubernetes/scheduler.conf
            - name: score
              mountPath: /etc/kubernetes/scheduler-score
            - name: scheduler-conf
              mountPath: /etc/kubernetes/scheduler-conf
      hostNetwork: false
      hostPID: false
      volumes:
        - name: kubeconfig
          hostPath:
            path: /etc/kubernetes/scheduler.conf
            type: FileOrCreate
        - name: scheduler-conf
          configMap:
            name: scheduler-conf
        - name: score
          configMap:
            name: scheduler-score

```

**Comment by Wenshiqi222** [comment]
> > i was wondering since the container volumeMount is the configMap, the PATH "/etc/kubernetes/scheduler.conf" can be tell by the K8s？Or is this the reason why my container is Back-off？
> 
> @Wenshiqi222
> /etc/kubernetes/scheduler.conf (contains auth data ) is used for connecting to k8s api server. You can use host path volume to mount your master's /etc/kubernetes/ into your scheduler's container.
> 
> ```yaml
>          ...
>         - name: kubernetes-config
>           hostPath:
>             path: /etc/kubernetes
>           ...
>           volumeMounts:
>             - name: kubernetes-config
>               mountPath: /etc/kubernetes
> ```

i did as you suggested，still got the PATH wanning，here is my schedulerPod.yaml:
```
    spec:
      serviceAccountName: my-scheduler     
      volumes:
      - name: scheduler-config
        hostPath:
          path: /etc/kubernetes
      containers:
      - command:
        - kube-scheduler
        - --config=/etc/kubernetes/qos-scheduler-config.yaml
        - --kubeconfig=scheduler.conf
        image: wenshiqi/my-kube-scheduler:2.0
        imagePullPolicy: IfNotPresent
       # livenessProbe:
       #   httpGet:
       #     path: /healthz
       #     port: 10251
       #   initialDelaySeconds: 15
        name: kube-second-scheduler
       # readinessProbe:
       #   httpGet:
       #     path: /healthz
       #     port: 10251
        resources:
          requests:
            cpu: '50m'      
        volumeMounts: 
        - name: scheduler-config
          mountPath: /etc/kubernetes
```
and i didi copy the qos-scheduler-config.yaml file to the path:/etc/kubernetes/ ,and in the PATH there also has the scheduler.conf,but still got the error:
```
[root@master myScheduler]# kubectl logs -f -n kube-system my-scheduler1-84fb5449cb-9zppl 
I0829 03:17:31.301427       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0829 03:17:31.301613       1 registry.go:150] Registering EvenPodsSpread predicate and priority function
I0829 03:17:31.567112       1 serving.go:313] Generated self-signed cert in-memory
open /etc/kubernetes/qos-scheduler-config.yaml: no such file or directory
```
i was really confused
