### ISSUE TITLE
podgroup termination for AI workloads

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/scheduler-plugins#444]
Hello,

We would like to have a feature where if one of the pod(s) in podgroup has a crash then the entire podgroup should be terminated.

quick test to reproduce:

- apply podgroup:

```
# podgroup.yaml
apiVersion: scheduling.sigs.k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: pg1
spec:
  scheduleTimeoutSeconds: 10
  minMember: 3
```
- apply deployment
```
# deploy.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
        pod-group.scheduling.sigs.k8s.io: pg1
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.6
```
- Delete one of the pods and the deployment controller restarts a new pod

```
(base) asmalvan@mcad-dev:~/co-schd-v2/scheduler-plugins/manifests/install/charts$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
pause-64f58bcb89-vwfrq   1/1     Running   0          4s
pause-64f58bcb89-xf98l   1/1     Running   0          4s
pause-64f58bcb89-xx5bp   1/1     Running   0          4s
(base) asmalvan@mcad-dev:~/co-schd-v2/scheduler-plugins/manifests/install/charts$ kubectl delete pod pause-64f58bcb89-vwfrq
pod "pause-64f58bcb89-vwfrq" deleted
(base) asmalvan@mcad-dev:~/co-schd-v2/scheduler-plugins/manifests/install/charts$ kubectl get pods
NAME                     READY   STATUS    RESTARTS   AGE
pause-64f58bcb89-7qczq   1/1     Running   0          12s
pause-64f58bcb89-xf98l   1/1     Running   0          32s
pause-64f58bcb89-xx5bp   1/1     Running   0          32s
```
