### ISSUE TITLE
Configure bin-packing in Helm chart

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/scheduler-plugins#448]
Hello,

Any pointers on how to enable packing? I read kubernetes has [bin-packing](https://kubernetes.io/docs/concepts/scheduling-eviction/resource-bin-packing/#enabling-bin-packing-using-requestedtocapacityratio), how do we use such plugins in co-scheduler using helm commands?

**Comment by asm582** [comment]
@Huang-Wei Sorry for tagging, any pointers that you can share would be of great help, and do you think should packing be enabled by default?

**Comment by Huang-Wei** [comment]
Bin-packing can be achieved by configuring the in-tree `RequestedToCapacityRatio` plugin, generally, it should work using the following config:

```yaml
  plugins:
    score:
      enabled:
      - name: RequestedToCapacityRatio
        weight: 10 # a user-defined weight
      disabled:
      - name: NodeResourcesLeastAllocated
  pluginConfig:
  - name: RequestedToCapacityRatio
    args:
      shape:
      - utilization: 0
        score: 0
      - utilization: 100
        score: 10
      # resources: # without explicitly defining resources, the above config will apply to cpu and memory
```

Please note that it's tangant with enabling co-scheduling (or whatever other plugin) or not. It's just a standalone plugin that favors nodes with higher resource utilization than others.

I don't have cycles to look into how to reflect the config into Helm charts, but it's doable. Help is wanted.

/help
