### ISSUE TITLE
[Question] Problem migrating from algorithmSource to scheduler profiles.

### ISSUE THREAD

**Issue by vcozzolino** [kubernetes-sigs/scheduler-plugins#451]
I have been following this tutorial https://developer.ibm.com/articles/creating-a-custom-kube-scheduler/ to extend the basic Kubernetes scheduler with some extra decision logic.

After a lot of browsing trying to fix wrong Kind types, apiVersions etc.., I found out that the use of `algorithmSource` is deprecated for Kubernetes v1.19. What I'm using is the configuration below:

```
 # content of the file passed to "--config"
 apiVersion: kubescheduler.config.k8s.io/v1beta1
 kind: KubeSchedulerConfiguration
 clientConnection:
   kubeconfig: "/var/run/kubernetes/scheduler.kubeconfig"
 algorithmSource:
   policy:
     file:
       path: "/root/config/scheduler-extender-policy.json"

```

with policy:
```
{
    "kind" : "Policy",
    "apiVersion" : "v1",
    "extenders" : [{
        "urlPrefix": "http://localhost:8888/",
        "filterVerb": "filter",
        "prioritizeVerb": "prioritize",
        "weight": 1,
        "enableHttps": false
    }]
}
```

As far as I understood, we should use scheduler profiles to achieve the same outcome. However, I was not able to find anywhere a tutorial explaining how possibly do this. My goal is to reach exactly what the tutorial achieves, ergo having my external web service hook into some specific scheduling actions of the Kubernetes scheduler so that I can work on my custom logic without touching the scheduler itself.

Is this ultimately possible?
