### ISSUE TITLE
How can i test the Qos-Plugins on my own k8s environment？

### ISSUE THREAD

**Issue by Wenshiqi222** [kubernetes-sigs/scheduler-plugins#59]
Since i successfully start the Qos-Plugins，and i wanna test if the Qos-based selection will work when the priority of two pods are equal.So i prepare the two files, one is the priority file to make sure that the following two pods'priority are equal,the other file is the  pod files for testing,which is set the same priority and the second pod is written with Guaranteed class.
**priority.yaml**
```
 apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata: 
  name: priority-test
value: 1000000
globalDefault: false
description: "This priority class should be used for testing the qos-scheduling "
```
**pod.yaml**
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx1
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  priorityClassName: priority-test
  schedulerName: my-scheduler1
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        memory: "10Mi"
        cpu: "100m"
      limits:
        memory: "10Mi"
        cpu: "100m"
  priorityClassName: priority-test
  schedulerName: my-scheduler1
```
But it seems impossible to see which pod is scheduled fisrtly, cause they looks like being scheduled at the same time,
to test this plugin,how can i design my experiment? Or is there any other command to check the scheduleling logs? for now,**kubectl logs** and **kubectl descirbe**  cannot see the scheduling sequence .
