### ISSUE TITLE
kube-scheduler-plugins cannot be started due to insufficient permissions.

### ISSUE THREAD

**Issue by WVenus** [kubernetes-sigs/scheduler-plugins#642]
### Area

- [ ] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

I use this configuration example, but my kube-scheduler has an error log and cannot be started due to lack of permissions.

```yaml
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
profiles:
  - schedulerName: network-aware-scheduler
    plugins:
      queueSort:
        enabled:
          - name: TopologicalSort
        disabled:
          - name: "*"
      preFilter:
        enabled:
          - name: NetworkOverhead
      filter:
        enabled:
          - name: NetworkOverhead
      score:
        disabled: # Preferably avoid the combination of NodeResourcesFit with NetworkOverhead
          - name: NodeResourcesFit
        enabled: # A higher weight is given to NetworkOverhead to favor allocation schemes with lower latency.
          - name: NetworkOverhead
            weight: 5
          - name: BalancedAllocation
            weight: 1
    pluginConfig:
      - name: TopologicalSort
        args:
          namespaces:
            - "default"
      - name: NetworkOverhead
        args:
          namespaces:
            - "default"
          weightsName: "UserDefined" # The respective weights to consider in the plugins
          networkTopologyName: "net-topology-test" # networkTopology CR to be used by the plugins
```

```text
E0921 06:51:18.486853       1 reflector.go:140] github.com/diktyo-io/appgroup-api/pkg/generated/informers/externalversions/factory.go:119: Failed to watch *v1alpha1.AppGroup: failed to list *v1alpha1.AppGroup: appgroups.appgroup.diktyo.x-k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "appgroups" in API group "appgroup.diktyo.x-k8s.io" at the cluster scope
```

I have performed the following steps:
![image](https://github.com/kubernetes-sigs/scheduler-plugins/assets/39941928/fb7bd5fa-9ed2-436b-ba9c-e1997673db5d)

### What did you expect to happen?

I hope it won't fail to start due to insufficient permissions.

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
</details>

### Scheduler Plugins version

<details>
v0.26.7
</details>
