### ISSUE TITLE
Nginx pods are in pending state, while testing cosheduling.

### ISSUE THREAD

**Issue by JibinNajeeb** [kubernetes-sigs/scheduler-plugins#70]
Tested in a cluster with 1 master and 1 worker.
Below are the steps I did,
1. Created kube-schedule-configuration.yml with below contents
```
[apiVersion: kubescheduler.config.k8s.io/v1beta1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"   #scheduler.conf file from my kubernetes master
profiles:
- schedulerName: default-scheduler
  plugins:
    queueSort:
      enabled:
        - name: Coscheduling
      disabled:
        - name: "*"
    preFilter:
      enabled:
        - name: Coscheduling
    permit:
      enabled:
        - name: Coscheduling
    reserve:
      enabled:
        - name: Coscheduling
```
2. Executed below steps
```
docker build -f ./build/scheduler/Dockerfile -t test/test-scheduler:v1 . #(kube-schedule-configuration.yml and /etc/kubernetes/scheduler.conf is inside docker image)
docker push test/test-scheduler:v1
```
3. Followed the steps in this link to create a second scheduler (https://kubernetes.io/docs/tasks/extend-kubernetes/configure-multiple-schedulers/)
```
....
  spec:
      serviceAccountName: my-scheduler
      containers:
      - command:
        - /usr/local/bin/kube-scheduler
        - --address=0.0.0.0
        - --leader-elect=false
        - --scheduler-name=my-scheduler
        - --config=kube-schedule-configuration.yml
        image: test/test-scheduler:v1
.....
```
4. Deployed the below replicaSet with scheduler as my-scheduler
```
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      name: nginx
      labels:
        app: nginx
        pod-group.scheduling.sigs.k8s.io/name: nginx
        pod-group.scheduling.sigs.k8s.io/min-available: "3"
    spec:
      schedulerName: my-scheduler
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
```
5, After deploying nginx, all pods are in pending state. Couldnt make a single pod running with any plugin configuration I tried .
