### ISSUE TITLE
schduler-plugin calls the filter interface but does not call (sort,score) types of interfaces

### ISSUE THREAD

**Issue by guojianyu** [kubernetes-sigs/scheduler-plugins#759]
### Area

- [X] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### What happened?

schduler-plugin calls the filter interface but does not call (sort,score) types of interfaces.
**The code is as follows：**
```
package main
import (
	"context"
	"fmt"
	"os"
	"time"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/component-base/cli"
	_ "k8s.io/component-base/logs/json/register" // for JSON log format registration
	_ "k8s.io/component-base/metrics/prometheus/clientgo"
	_ "k8s.io/component-base/metrics/prometheus/version" // for version metric registration
	"k8s.io/klog/v2"
	"k8s.io/kubernetes/cmd/kube-scheduler/app"
	"k8s.io/kubernetes/pkg/scheduler/framework"
)

func main() {
	myPlugin := app.WithPlugin("nodeAge", New)

	command := app.NewSchedulerCommand(myPlugin)
	code := cli.Run(command)
	os.Exit(code)
}

type NodeAge struct {
	handle framework.Handle
}

func (pl *NodeAge) Name() string {
	return "nodeAge"
}

var _ = framework.ScorePlugin(&NodeAge{})
var _ = framework.QueueSortPlugin(&NodeAge{})
var _ = framework.FilterPlugin(&NodeAge{})
var _ = framework.PreScorePlugin(&NodeAge{})
var _ = framework.PreFilterPlugin(&NodeAge{})

func (c *NodeAge) PreFilter(ctx context.Context, state *framework.CycleState, pod *v1.Pod) (*framework.PreFilterResult, *framework.Status) {
	klog.Infof("PreFilter is called for Pod: %s/%s", pod.Namespace, pod.Name)
	return nil, nil
}

func (c *NodeAge) PreFilterExtensions() framework.PreFilterExtensions {
	return nil
}


func (pl *NodeAge) Filter(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeInfo *framework.NodeInfo) *framework.Status {
	klog.Infof("filter pod: %v", pod.Name)
	//klog.Infof("filter state: %v", state)
	node := nodeInfo.Node()
	if node == nil {
		return framework.NewStatus(framework.Error, "node not found")
	}

	return framework.NewStatus(framework.Success, "Node: "+node.Name)
}

func getPriority(pod *v1.Pod) int {

	return 0 // TODO: Replace with actual logic
}

func (pl *NodeAge) Less(pod1, pod2 *framework.QueuedPodInfo) bool {
	klog.Infof("Less: %v,%v", pod1, pod2)
	priority1 := getPriority(pod1.Pod)
	priority2 := getPriority(pod2.Pod)
	if emer, ok := pod1.Pod.Labels["emergency"]; ok && emer == "red" {
		return true
	} else {
		return priority1 > priority2
	}
	//return priority1 > priority2 
}

func (p *NodeAge) PreScore(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodes []*v1.Node) *framework.Status {
	klog.Infof("PreScore plugin executed for Pod %s/%s", pod.Namespace, pod.Name)
	for _, node := range nodes {
		klog.Infof("Node available: %s", node.Name)
	}
	return framework.NewStatus(framework.Success, "")
}

func (pl *NodeAge) Score(ctx context.Context, state *framework.CycleState, pod *v1.Pod, nodeName string) (int64, *framework.Status) {
	nodeInfo, err := pl.handle.SnapshotSharedLister().NodeInfos().Get(nodeName)
	if err != nil {
		return 0, framework.AsStatus(fmt.Errorf("getting node %q from Snapshot: %w", nodeName, err))
	}
	tsCreation := nodeInfo.Node().ObjectMeta.CreationTimestamp.Second()
	tsCurrent := time.Now().Second()
	score := 0
	if tsCurrent-tsCreation < 15*3600*24 {
		score += 1
		klog.InfoS("node get score", "pod_name", pod.Name, "current node", nodeInfo.Node().Name, "node age(days)", (tsCurrent-tsCreation)/3600/24)
	} else {
		klog.InfoS("node can't get score", "pod_name", pod.Name, "current node", nodeInfo.Node().Name, "node age(days)", (tsCurrent-tsCreation)/3600/24)
	}
	return int64(score), nil
}

func (pl *NodeAge) ScoreExtensions() framework.ScoreExtensions {
	return pl
}

func (pl *NodeAge) NormalizeScore(ctx context.Context, state *framework.CycleState, pod *v1.Pod, scores framework.NodeScoreList) *framework.Status {
	return framework.NewStatus(framework.Success, "")
}

func New(_ runtime.Object, h framework.Handle) (framework.Plugin, error) {
	return &NodeAge{handle: h}, nil
}
```

**The Scheduler_config.yaml is as follows:**
```
apiVersion: kubescheduler.config.k8s.io/v1
leaderElection:
  leaderElect: true
clientConnection:
  kubeconfig: "/etc/kubernetes/scheduler.conf"
kind: KubeSchedulerConfiguration
profiles:
  - schedulerName: my-scheduler
    plugins:
      preFilter:
        enabled:
        - name: nodeAge
      filter:
        enabled:
        - name: nodeAge
      preScore:
        enabled:
        - name: nodeAge
      score:
        enabled:
        - name: nodeAge
      queueSort:
        enabled:
        - name: nodeAge
        disabled:
        - name: "*"
```
**scheduler-deploy.yaml:**
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      schedulerName: my-scheduler
      containers:
      - image: nginx
        imagePullPolicy: IfNotPresent       
        name: nginx

```
The scheduler log output is as follows:
![image](https://github.com/kubernetes-sigs/scheduler-plugins/assets/21234963/13a6e375-f454-48ab-81bf-722907eb1740)

Is this a problem with my code or something else? If it is a code problem, how can I fix it? Thank you very much!! 🙏

### What did you expect to happen?

Sort and Score interface can be called normally.

### Anything else we need to know?

I upgraded the scheduler-plugin to the latest version with the same problem

### Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```
![image](https://github.com/kubernetes-sigs/scheduler-plugins/assets/21234963/482ade87-5c9a-4ef2-8aff-1d846e29a85a)

</details>

### Scheduler Plugins version

<details>

</details>
release-1.26
