### ISSUE TITLE
feature: add more field in preemption toleration policy

### ISSUE THREAD

**Issue by googs1025** [kubernetes-sigs/scheduler-plugins#839]
Currently, the preemption toleration policy only has minimum-preemptable-priority and toleration-seconds.
like as follows:

```yaml
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: toleration-policy-sample
  annotations:
    preemption-toleration.scheduling.x-k8s.io/minimum-preemptable-priority: "10000"
    preemption-toleration.scheduling.x-k8s.io/toleration-seconds: "3600"
value: 8000

```

Now I want to add more fields: 
like: 
We can exclude Pods in a specific namespace from being preempted
`preemption-toleration.scheduling.x-k8s.io/excluded-namespaces: "kube-system,default,critical-ns"`

Maybe there are other filters?
