### ISSUE TITLE
Error: initializing plugin `"PreemptionToleration"`: got args of type `*config.PreemptionTolerationArgs`, want `*PreemptionTolerationArgs`

### ISSUE THREAD

**Issue by a7i** [kubernetes-sigs/scheduler-plugins#876]
### Area

- [x] Scheduler
- [ ] Controller
- [ ] Helm Chart
- [ ] Documents

### Other components

PreemptionToleration

### What happened?

Faced an error when kube-scheduler starts up

error:
```
Error: initializing profiles: creating profile for scheduler name custom-scheduler: initializing plugin "PreemptionToleration": got args of type *config.PreemptionTolerationArgs, want *PreemptionTolerationArgs
```

### What did you expect to happen?

The plugin to get initialized without issues

### How can we reproduce it (as minimally and precisely as possible)?

```
package main

import (
	"k8s.io/component-base/cli"
	_ "k8s.io/component-base/logs/json/register"         // for JSON log format registration
	_ "k8s.io/component-base/metrics/prometheus/version" // for version metric registration

	"k8s.io/kubernetes/cmd/kube-scheduler/app"
	"sigs.k8s.io/scheduler-plugins/pkg/preemptiontoleration"

	_ "sigs.k8s.io/scheduler-plugins/apis/config/scheme" // ensure scheme package is initialized.
)

func main() {
	command := app.NewSchedulerCommand(
		app.WithPlugin(preemptiontoleration.Name, preemptiontoleration.New),
	)

	cli.Run(command)
}
```

go.mod:
```
go 1.23

require (
	k8s.io/component-base v0.30.6
	k8s.io/kubernetes v1.30.6
	sigs.k8s.io/scheduler-plugins v0.30.6
)
```

```
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: custom-scheduler
      plugins:
        score:
          enabled:
          - name: PodTopologySpread
            weight: 5 # (default is 2) - prioritize over NodeResourcesFit which has default weight of 1
        postFilter:
          enabled:
          - name: PreemptionToleration
          disabled:
          - name: DefaultPreemption
```

### Kubernetes version

<details>

```console
$ kubectl version
Client Version: v1.30.5
Server Version: v1.30.6
```

</details>

### Scheduler Plugins version

<details>
v0.30.6
</details>
