### ISSUE TITLE
Trimaran TargetLoadPacking not working

### ISSUE THREAD

**Issue by tieungao88** [kubernetes-sigs/scheduler-plugins#880]
Hi,
I'm testing Trimaran scheduler. But I see that not working for me.
The senario:
- Environment: Aws EKS 1.30
- Trimaran scheduler config:
```yaml
---
apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
  resourceNamespace: default
  resourceName: scheduler-plugins-scheduler
profiles:
- schedulerName: trimaran
  plugins:
    score:
      enabled:
        - name: TargetLoadPacking
  pluginConfig:
    - name: TargetLoadPacking
      args:
        defaultRequests:
          cpu: "100m"
        defaultRequestsMultiplier: "1"
        metricProvider:
          type: Prometheus
          address: "http://dev-ext-prometheus-kube-pr-prometheus.prometheus.svc.cluster.local:9090"
        targetUtilization: 50
```
- I have one deployment:
```yaml
apiVersion: scheduling.x-k8s.io/v1alpha1
kind: PodGroup
metadata:
  name: ubuntu-group
spec:
  minMember: 1
  scheduleTimeoutSeconds: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-hog-active-01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpu-hog-active-01
  template:
    metadata:
      labels:
        app: cpu-hog-active-01
        scheduling.x-k8s.io/pod-group: ubuntu-group
      annotations:
        scheduling.x-k8s.io/pod-group: ubuntu-group
    spec:
      schedulerName: trimaran
      nodeSelector:
        workload-type: app-schplugin
      tolerations:
        - key: workload-type
          operator: Equal
          value: app-schplugin
          effect: NoSchedule
      containers:
      - name: cpu-hog-active-01
        image: busybox
        resources:
          requests:
            cpu: "100m"
          # limits:
          #   cpu: "1500m"
        command: ["/bin/sh", "-c"]
        args:
        - |
          N=$(nproc)
          for i in $(seq 1 $N); do
            yes > /dev/null &
          done
          wait
```
The first, I scale deployment to one pod, after 5 mins. The cpu of node is ~ 100%:

![Image](https://github.com/user-attachments/assets/aff1ae0c-bb92-4b2f-8bc5-1fe5fd17c5a1)
But when I scale new pod, the new pod is schedule to the same node !.

<img width="1184" alt="Image" src="https://github.com/user-attachments/assets/22f7adfb-05eb-4a9e-9761-eb957356f931" />

Please help me.

Thanks.
